theme: jekyll-theme-minimal
title: Catatan Khaerul Anas
description: Website ini berisi profil, catatan, dan proyek pembelajaran saya di bindang TI 
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
