theme: jekyll-theme-minimal
title: Catatan Khaerul Anas
description: Website ini berisi profil, catatan, dan proyek pembelajaran saya di bidang TI 
show_downloads: True
navigation:
  - title: Beranda
    url: /
  - title: Profil
    url: profil
  - title: Proyek
    url: proyek
  - title: Catatan
    url: catatan
  - title: Buku
    url: buku
